image: docker
services:
  - docker:20-dind

build:
  script:
    # - docker login $CI_REGISTRY -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD
    - apk add --no-cache docker-compose
    - docker-compose build
    - docker-compose up -d
